# Generated by Django 5.1.1 on 2024-10-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.PositiveIntegerField()),
                ('service_code', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('average_deviation', models.FloatField()),
            ],
        ),
    ]
